name: Publish Python Package

on: push
jobs:
  # build:
  #   name: Build distribution 📦
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: "3.9"

  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    # needs:
    # - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/derive_action_signing  # Replace <package-name> with your PyPI project name
    permissions:
      contents: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Publish PyPi package
      uses: code-specialist/pypi-poetry-publish@v1
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_REGISTRY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
