name: Unit-test

on: push
jobs:
  build:
    name: Unit-test 🎯
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install pytest
      run: >-
        python3 -m
        pip install
        pytest requests
        --user

    - name: Install project dependencies
      run: pip install -r requirements.txt

    - name: Unit-Test
      run: pytest -s
